<?php include('header.php'); ?>
<div id="navigation">
				<ul>
					<li><a href="set_data_path.php">Upload data</a></li>
					<li><a href="results_overview.php">Results overview</a></li>
					<li><a href="cleavage_site_statistics.php">Cleavage site statistics</a></li>
					<li><a href="weblogo.php">Weblogo</a></li>
					<li><a href="downloads.php">Downloads</a></li>
				</ul>
			</div>
			<div id="content">
				<h2>Imprint</h2>
				<p>
                    This page was created by Matthias Stahl, member of the Sieber group at <a href="http://www.oc2.ch.tum.de">TU München</a>. The PSM analyzer core was programmed by Malte Gersch and Matthias Stahl, <a href="http://www.tum.de">TU München</a>. The website is hosted at <a href="http://www.uberspace.de">uberspace.de</a>.
					<br /><br />
                    Banner photograph: Small sailboat - 3D render (© Elenarts, Fotolia)
                    <br /><br />
					While no permanent records are kept of submitted data, we cannot undertake to guarantee that data sent to Protein|Clpper remains secure. Moreover, no guarantees whatsoever are provided about data generated by Protein|Clpper. This website uses "cookies" to store user related peptide data.
					<br /><br />
				</p>
				<p>
					This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google. <a href="https://tools.google.com/dlpage/gaoptout?hl=en">More information on Google analytics opt-out</a>.
				</p>
				<p>
					<br /><br />
					For a detailed imprint, please see the <a href="http://www.oc2.ch.tum.de">Website of AK Sieber</a>
				</p>
			</div>
<?php include('footer.php'); ?>